<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net46</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IllusionModdingAPI.HS2API" Version="1.45.1"/>
	</ItemGroup>

	<Import Project="..\Core_BetterPenetration\Core_BetterPenetration.projitems" Label="Shared" />
</Project>